### ISSUE TITLE
Use actual image when thumbnail is not present

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-media#174]
### Tasks done
- Use actual image when thumbnail is not present
- Show full image in the carousel
- Ability to download a file and open a file both (including for files with thumbnails missing)

**Comment by petmongrels** [comment]
changes in avni-server, avni-media, avni-etl

**Comment by AchalaBelokar** [comment]
- [ ] not showing the analytic db value
- [ ]

**Comment by AchalaBelokar** [comment]
- [x] able to download the image through the the thumbnail 
- [x] able to download the image through the carousel
- [ ] try to download multiple images through download button it contains empty folder not contains any images
- [ ] after selecting the images try to download the image

**Comment by himeshr** [comment]
@petmongrels we have avni-media config in pre-release configured to work with S3 Urls for media content within the bucket "prerelease-user-media". Replacing them with Prod configurations will break convention we have followed across the system configuration and is not a good idea from long term maintenance perspective.

AVNI_MEDIA_S3_BUCKET_NAME: prerelease-user-media
AVNI_MEDIA_S3_ZIP_UPLOAD_BUCKET_NAME: prerelease-user-media

**Comment by himeshr** [comment]
For the issue _"try to download multiple images through download button it contains empty folder not contains any images"_
We need to do away with usage of configured AVNI_MEDIA_S3_BUCKET_NAME info, and instead use Media URL specific AVNI_MEDIA_S3_BUCKET_NAME to get this working.

This would then start working, as we give all our AWS_ACCESS_KEYS privileges across all Buckets and their content objects and do not restrict them to a specific env (Prod, prerelease, staging, etc..) Buckets.
